Added translations for social media username examples
ZeitOnline/zeit.locales pull request #12
Opened 2016-11-25 14:37 UTC by knutgoetz

2016-11-25 15:39 UTC, sallner reviewed
Bis auf die angegebene Änderung sieht das problemlos aus, denke ich.

2016-11-25 15:39 UTC, sallner commented on src/zeit/locales/zeit.cms.pot
> -msgstr ""
Das scheint zumindest noch in der angegebenen Datei verwendet zu werden. Vielleicht doch lieber behalten.

2016-11-28 07:25 UTC, icemac requested changes
Ich habe einen Änderungswunsch. Wenn https://github.com/ZeitOnline/zeit.locales/pull/12 so wie von mir vorgeschlagen wird, muss die Übersetzung hier nochmals gemacht werden.

2016-11-28 07:25 UTC, icemac commented on src/zeit/locales/de/LC_MESSAGES/zeit.cms.po
>  "Last-Translator: Wolfgang Schnerring <wolfgang.schnerring@zeit.de>\n"
@knutgoetz Hier sollte dein Name stehen, da du die Datei als letztes angefasst hast. Bitte trage deinen Namen in deinen Poedit-Einstellungen ein, damit das automatisch gemacht wird.

2016-12-06 10:32 UTC, knutgoetz commented on src/zeit/locales/de/LC_MESSAGES/zeit.cms.po
>  "Last-Translator: Wolfgang Schnerring <wolfgang.schnerring@zeit.de>\n"
ah okay danke, habe ich gemacht

2016-12-06 10:33 UTC, closed without merging