MAINT: Update i18n
ZeitOnline/zeit.locales pull request #31
Opened 2018-03-16 14:15 UTC by mstoltenburg

following the documentation at http://buildbert.zeit.de/job/vivi-deployment/ws/build/doc/development/translations.html

2018-03-19 08:11 UTC, wosc requested changes
Ahoi, der Diff ist leider ziemlich noisy und verwirrend (selbst mit [Nachhilfe](https://github.com/ZeitOnline/zeit.locales/commit/243ed7694473c4f25528199208477830f31ef692)). Was ist denn das eigentliche Ziel?

Und wenn ich mich nicht total täusche, kommen hier auch Übersetzungen wieder rein, die gar nicht mehr verwendet werden, z.B. "Nur die ersten x Schlagwörter werden angezeigt" (wurde mit TMS-173 entfernt), "Keyword-Vorschläge Google News" (wurde Anfang Februar weil unbenutzt entfernt) oder der ganze Kram über die vivi-basierten Quiz-Objekte (wurde mitte Februar dito entfernt). Die sollten denke ich in jedem Fall wieder raus. :)

2018-03-19 09:09 UTC, mstoltenburg commented
Also, das eigentlich Ziel ist es, für zwei anstehende Tickets zusätzliche Vivi-Felder mit Übersetzung hinzuzufügen. Damit dort die Änderungen nicht komplett unübersichtlich werden, wollte ich als Vorarbeit mal die Übersetzungen auf einen aktuellen Stand bringen.

Ich sehe nicht, dass `Nur die ersten ${keywords_shown} Schlagwörter …` und `Keyword-Vorschläge (Google News)` hinzugefügt werden. Es scheint eine Eigenart von poedit zu sein, entfernte Übersetzungen als _Back-Up_ aufzuheben, um sie bei Wiederverwendung aktivieren zu können. Diese Strings sind alle auskommentiert an das Ende der Datei gewandert (sie beginnen immer mit `#~ msgid …`.

Es sollten mit diesem PR eigentlich keine Übersetzungen hinzugefügt werden, sondern nur die Übersetzungen mit dem aktuellen Code synchronisiert werden.  Auffällig fand ich, dass so viele Übersetzungen für `zeit/content/quiz/…` und `zeit/imp/…` rausgeflogen sind. Hat das seine Richtigkeit?

2018-03-20 07:29 UTC, wosc commented
Ohje dann lügt mich der diff ja total an... :thinking: und/oder ich bediene ihn falsch. Richtig wäre evtl `git diff master..maintain-localization` anstatt einfach nur `git diff maintain-localization`. Danke git.

Aber ja, es ist völlig richtig, dass z.c.quiz und zeit.imp rausfliegen, die wurden ausm vivi entfernt, weil sie nicht mehr verwendet werden.

2018-03-20 07:30 UTC, wosc approved these changes

2018-03-20 07:30 UTC, merged